### ISSUE TITLE
Can you create a release? :)

### ISSUE THREAD

**Issue by tmsrise** [GrandpaGameHacker/ClassDumper3#1]
You sent me a link to Class Dumper 2 probably over a year ago in the CE discord and I recently got back into RE. This would be nice to have. Thanks!

**Comment by GrandpaGameHacker** [comment]
Oh yeah, I've sort of paused development but I might get back into it
version 3 will be its own process so its going to be a bit more involved to get it to function correctly lol

**Comment by GrandpaGameHacker** [comment]
@tmsrise I have started working on this again
